---
- name: "Execute 'terraform destroy'"
  community.general.terraform:
    project_path: "{{ terraform_project_path }}"
    state: absent
    force_init: "{{ terraform_force_init }}"
    variables: "{{ terraform_variables | default(omit) }}"
    variables_files: "{{ terraform_variables_files | default(omit) }}"
    state_file: "{{ terraform_state_file | default(omit) }}"
    targets: "{{ terraform_targets | default(omit) }}"
    workspace: "{{ terraform_workspace | default(omit) }}"
    parallelism: "{{ terraform_parallelism | default(omit) }}"
    purge_workspace: "{{ terraform_purge_workspace | default(omit) }}"
    binary_path: "{{ terraform_binary_path | default(omit) }}"
    lock: "{{ terraform_lock }}"
    lock_timeout: "{{ terraform_lock_timeout | default(omit) }}"
    plugin_paths: "{{ terraform_plugin_paths | default(omit) }}"
